# docker-compose.yml
# squ_488ecf81baf98e488f994db9ef00b4effafd6e23
services:
  backend:
    build: 
      context: ./server
    container_name: hr-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env   # Loads your MongoDB URL from the server folder
    restart: always

  frontend:
    build: 
      context: ./frontend
    container_name: hr-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube-server
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
