# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-backend
spec:
  replicas: 2      # Auto-creates 2 copies of your backend for high availability!
  selector:
    matchLabels:
      app: hr-backend
  template:
    metadata:
      labels:
        app: hr-backend
    spec:
      containers:
      - name: backend
        image: jeffrinjojo/hr-backend:latest    # We will update this when we push to Docker Hub
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: hr-app-secrets
              key: MONGODB_URL

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: hr-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP   # Internal routing only (secure)
